<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Update="Resources\CulturalTexts.Designer.cs">
      <DependentUpon>CulturalTexts.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\CulturalTexts.en.Designer.cs">
      <DependentUpon>CulturalTexts.en.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Messages.Designer.cs">
      <DependentUpon>Messages.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Messages.en.Designer.cs">
      <DependentUpon>Messages.en.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\ViewTexts.Designer.cs">
      <DependentUpon>ViewTexts.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\ViewTexts.en.Designer.cs">
      <DependentUpon>ViewTexts.en.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\CulturalTexts.en.resx">
      <LastGenOutput>CulturalTexts.en.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CulturalTexts.resx">
      <LastGenOutput>CulturalTexts.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Messages.en.resx">
      <LastGenOutput>Messages.en.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Messages.resx">
      <LastGenOutput>Messages.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ViewTexts.en.resx">
      <LastGenOutput>ViewTexts.en.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ViewTexts.resx">
      <LastGenOutput>ViewTexts.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>
