<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>Neo.Bpms.Api</PackageId>
    <Authors>Javad Seyedi</Authors>
    <Description>Neo BPMS API - Monitoring, Dashboard, Forms, Reports, Process APIs</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="MinVer" PrivateAssets="All" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Neo.Bpms.Domain\Neo.Bpms.Domain.csproj" />
    <ProjectReference Include="..\Neo.Bpms.Infrastructure\Neo.Bpms.Infrastructure.csproj" />
    <ProjectReference Include="..\Neo.Bpms.Application\Neo.Bpms.Application.csproj" />
    <ProjectReference Include="..\Neo.Bpms.UI.MVC\Neo.Bpms.UI.MVC.csproj" />
    <ProjectReference Include="..\..\..\Neo\src\Neo.Endpoint\Neo.Endpoint.csproj" />
  </ItemGroup>

</Project>