namespace Neo.Bpms.UI.MVC.ViewModels.Tree;

public class HierarchicalJsTree
{
    /// <summary>
    /// will be autogenerated if omitted
    /// </summary>
    public string id { get; set; }
    /// <summary>
    /// node text
    /// </summary>
    public string text { get; set; }
    //		  /// <summary>
    //		  /// string for custom
    //		  /// </summary>
    //		  public string icon { get; set; }
    //			 state       : {
    //				 opened    : boolean  // is the node open
    //				 disabled  : boolean  // is the node disabled
    //				 selected  : boolean  // is the node selected
    //			 },
    /// <summary>
    /// array of strings or objects
    /// </summary>
    /// 

    public dynamic data { get; set; }
    public IList<HierarchicalJsTree> children { get; set; }
    //			 li_attr     : {}  // attributes for the generated LI node
    //			 a_attr      : {}  // attributes for the generated A node
}