//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Bpms.Domain.Entities.Cmmn.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Bpms.Domain.Entities.Cmmn.UI.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرطِ استایلِ فعال.
        /// </summary>
        public static string ActiveWhen {
            get {
                return ResourceManager.GetString("ActiveWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمول موجودیت مرتبط شده.
        /// </summary>
        public static string AssociatedEntityFormula {
            get {
                return ResourceManager.GetString("AssociatedEntityFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ پس زمینه.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام تأیید.
        /// </summary>
        public static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استایل.
        /// </summary>
        public static string ContextualStyle {
            get {
                return ResourceManager.GetString("ContextualStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پراپرتی خاص کنترل (key:value).
        /// </summary>
        public static string CustomProperty {
            get {
                return ResourceManager.GetString("CustomProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرطِ استایلِ خطر.
        /// </summary>
        public static string DangerWhen {
            get {
                return ResourceManager.GetString("DangerWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به جز.
        /// </summary>
        public static string DoesNotContain {
            get {
                return ResourceManager.GetString("DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام شود با.
        /// </summary>
        public static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان به انگلیسی.
        /// </summary>
        public static string EnLabelName {
            get {
                return ResourceManager.GetString("EnLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استایل وقتی مقدار false است.
        /// </summary>
        public static string FalseStyle {
            get {
                return ResourceManager.GetString("FalseStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستون‌های عرضی (1 تا 12).
        /// </summary>
        public static string GridColumns {
            get {
                return ResourceManager.GetString("GridColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستون‌های عرضی در صفحات خیلی بزرگ (1 تا 12).
        /// </summary>
        public static string GridColumnsExtraLarge {
            get {
                return ResourceManager.GetString("GridColumnsExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستون‌های عرضی در صفحات بزرگ (1 تا 12).
        /// </summary>
        public static string GridColumnsLarge {
            get {
                return ResourceManager.GetString("GridColumnsLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستون‌های عرضی در صفحات متوسط (1 تا 12).
        /// </summary>
        public static string GridColumnsMedium {
            get {
                return ResourceManager.GetString("GridColumnsMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستون‌های عرضی در صفحات کوچک (1 تا 12).
        /// </summary>
        public static string GridColumnsSmall {
            get {
                return ResourceManager.GetString("GridColumnsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتفاع (به پیکسل).
        /// </summary>
        public static string HeightInPixels {
            get {
                return ResourceManager.GetString("HeightInPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلاس آیکون.
        /// </summary>
        public static string IconClass {
            get {
                return ResourceManager.GetString("IconClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر آیکون.
        /// </summary>
        public static string IconImage {
            get {
                return ResourceManager.GetString("IconImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرطِ استایلِ اطلاع.
        /// </summary>
        public static string InfoWhen {
            get {
                return ResourceManager.GetString("InfoWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برابر با.
        /// </summary>
        public static string IsEqualTo {
            get {
                return ResourceManager.GetString("IsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نابرابر با.
        /// </summary>
        public static string IsNotEqualTo {
            get {
                return ResourceManager.GetString("IsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای مقدار.
        /// </summary>
        public static string IsNotNull {
            get {
                return ResourceManager.GetString("IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون مقدار.
        /// </summary>
        public static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد است.
        /// </summary>
        public static string IsPassword {
            get {
                return ResourceManager.GetString("IsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش اول مسیر (کنترلر).
        /// </summary>
        public static string LinkPathFirstPart {
            get {
                return ResourceManager.GetString("LinkPathFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش آخر مسیر (اکشن).
        /// </summary>
        public static string LinkPathLastPart {
            get {
                return ResourceManager.GetString("LinkPathLastPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام عملیات.
        /// </summary>
        public static string OperationName {
            get {
                return ResourceManager.GetString("OperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزینه.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر نوع صفحه.
        /// </summary>
        public static string PageSubType {
            get {
                return ResourceManager.GetString("PageSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع صفحه (Form/Report/Dashboard).
        /// </summary>
        public static string PageType {
            get {
                return ResourceManager.GetString("PageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌ی فرآیند.
        /// </summary>
        public static string ProcessId {
            get {
                return ResourceManager.GetString("ProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط خواندنی.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره‌ی بارگذاریِ مجدد (به میلی‌ثانیه).
        /// </summary>
        public static string RefreshEveryXMilliseconds {
            get {
                return ResourceManager.GetString("RefreshEveryXMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌ی طراحی.
        /// </summary>
        public static string ReportConfigurationId {
            get {
                return ResourceManager.GetString("ReportConfigurationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الزامی.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروتکل رابط سرویس.
        /// </summary>
        public static string ServiceInterfaceProtocol {
            get {
                return ResourceManager.GetString("ServiceInterfaceProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش پیدا کند.
        /// </summary>
        public static string ShowHide {
            get {
                return ResourceManager.GetString("ShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس فایل مرجع.
        /// </summary>
        public static string SourceFileAddress {
            get {
                return ResourceManager.GetString("SourceFileAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع شود با.
        /// </summary>
        public static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرطِ استایلِ موفق.
        /// </summary>
        public static string SuccessWhen {
            get {
                return ResourceManager.GetString("SuccessWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع شود.
        /// </summary>
        public static string Summable {
            get {
                return ResourceManager.GetString("Summable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌ی فعالیت.
        /// </summary>
        public static string TaskId {
            get {
                return ResourceManager.GetString("TaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دقت نمایش زمان.
        /// </summary>
        public static string TimeDisplayResolution {
            get {
                return ResourceManager.GetString("TimeDisplayResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استایل وقتی مقدار true است.
        /// </summary>
        public static string TrueStyle {
            get {
                return ResourceManager.GetString("TrueStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرطِ استایلِ هشدار.
        /// </summary>
        public static string WarningWhen {
            get {
                return ResourceManager.GetString("WarningWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض به درصد.
        /// </summary>
        public static string WidthPercentage {
            get {
                return ResourceManager.GetString("WidthPercentage", resourceCulture);
            }
        }
    }
}
