//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Bpms.UI.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CulturalTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CulturalTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Bpms.UI.Resources.Resources.CulturalTexts", typeof(CulturalTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط.
        /// </summary>
        public static string AverageOf {
            get {
                return ResourceManager.GetString("AverageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string CountOf {
            get {
                return ResourceManager.GetString("CountOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولین.
        /// </summary>
        public static string FirstOf {
            get {
                return ResourceManager.GetString("FirstOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین.
        /// </summary>
        public static string LastOf {
            get {
                return ResourceManager.GetString("LastOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیشینه.
        /// </summary>
        public static string MaxOf {
            get {
                return ResourceManager.GetString("MaxOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمینه.
        /// </summary>
        public static string MinOf {
            get {
                return ResourceManager.GetString("MinOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمانبندی های دیگر طراحی های این گزارش.
        /// </summary>
        public static string OtherConfigsSchedules {
            get {
                return ResourceManager.GetString("OtherConfigsSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انحراف معیار.
        /// </summary>
        public static string StandardDeviationOf {
            get {
                return ResourceManager.GetString("StandardDeviationOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر گزارش همین موجودیت به ازای هر داده نمودار.
        /// </summary>
        public static string SubReportOfThisEntityForEachChartRow {
            get {
                return ResourceManager.GetString("SubReportOfThisEntityForEachChartRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر گزارش همین موجودیت به ازای هر سطر تجمیعی.
        /// </summary>
        public static string SubReportOfThisEntityForEachRow {
            get {
                return ResourceManager.GetString("SubReportOfThisEntityForEachRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع.
        /// </summary>
        public static string SumOf {
            get {
                return ResourceManager.GetString("SumOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمانبندی های این طراحی گزارش.
        /// </summary>
        public static string ThisConfigSchedules {
            get {
                return ResourceManager.GetString("ThisConfigSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
