//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Bpms.UI.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Bpms.UI.Resources.Resources.ViewTexts", typeof(ViewTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما به این صفحه دسترسی ندارید..
        /// </summary>
        public static string AccessDeniedHeader {
            get {
                return ResourceManager.GetString("AccessDeniedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا: عدم دسترسی.
        /// </summary>
        public static string AccessDeniedTitle {
            get {
                return ResourceManager.GetString("AccessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی.
        /// </summary>
        public static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی از طریق گروه کاربری.
        /// </summary>
        public static string AccessViaUserGroup {
            get {
                return ResourceManager.GetString("AccessViaUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکشن.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن پوشه.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن فرمول.
        /// </summary>
        public static string AddFormula {
            get {
                return ResourceManager.GetString("AddFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت تنظیم جدید.
        /// </summary>
        public static string AddNewConfig {
            get {
                return ResourceManager.GetString("AddNewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن فیلتر جدید.
        /// </summary>
        public static string AddNewFilter {
            get {
                return ResourceManager.GetString("AddNewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن رکورد.
        /// </summary>
        public static string AddNewRecord {
            get {
                return ResourceManager.GetString("AddNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن قالب جدید.
        /// </summary>
        public static string AddNewTemplate {
            get {
                return ResourceManager.GetString("AddNewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن زیرگزارش.
        /// </summary>
        public static string AddPossibleSubReport {
            get {
                return ResourceManager.GetString("AddPossibleSubReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن طراحی.
        /// </summary>
        public static string AddReportConfig {
            get {
                return ResourceManager.GetString("AddReportConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن زمانبندی.
        /// </summary>
        public static string AddSchedule {
            get {
                return ResourceManager.GetString("AddSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد زیرگزارش.
        /// </summary>
        public static string AddSubReport {
            get {
                return ResourceManager.GetString("AddSubReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن ویجت.
        /// </summary>
        public static string AddWidget {
            get {
                return ResourceManager.GetString("AddWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابزارهای مدیریتی.
        /// </summary>
        public static string AdminTools {
            get {
                return ResourceManager.GetString("AdminTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر تجمیع.
        /// </summary>
        public static string AggregationFilter {
            get {
                return ResourceManager.GetString("AggregationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        public static string AllTitle {
            get {
                return ResourceManager.GetString("AllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال فیلتر.
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال تنظیمات.
        /// </summary>
        public static string ApplySettings {
            get {
                return ResourceManager.GetString("ApplySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال تنظیمات کاربران.
        /// </summary>
        public static string ApplyUserSettings {
            get {
                return ResourceManager.GetString("ApplyUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صعودی.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصیص دسترسی.
        /// </summary>
        public static string AssignAccess {
            get {
                return ResourceManager.GetString("AssignAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ پس زمینه.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایین.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد گروهی فرآیند.
        /// </summary>
        public static string BulkCreateProcess {
            get {
                return ResourceManager.GetString("BulkCreateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش گروهی موجودیت.
        /// </summary>
        public static string BulkEditEntity {
            get {
                return ResourceManager.GetString("BulkEditEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات گروهی.
        /// </summary>
        public static string BulkOperations {
            get {
                return ResourceManager.GetString("BulkOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر فایل.
        /// </summary>
        public static string ChangeFile {
            get {
                return ResourceManager.GetString("ChangeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر نوع زیر گزارش.
        /// </summary>
        public static string ChangeSubReportType {
            get {
                return ResourceManager.GetString("ChangeSubReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر نام کاربری و رمزعبور.
        /// </summary>
        public static string ChangeUsernameAndPassword {
            get {
                return ResourceManager.GetString("ChangeUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور کاربران.
        /// </summary>
        public static string ChangeUsersPassword {
            get {
                return ResourceManager.GetString("ChangeUsersPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمودار.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات نمودار.
        /// </summary>
        public static string ChartSettings {
            get {
                return ResourceManager.GetString("ChartSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع نمودار.
        /// </summary>
        public static string ChartType {
            get {
                return ResourceManager.GetString("ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب فایل.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کلاس.
        /// </summary>
        public static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالی کردن فرم فیلتر.
        /// </summary>
        public static string ClearFilterForm {
            get {
                return ResourceManager.GetString("ClearFilterForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات رنگ رکوردها.
        /// </summary>
        public static string ColorsSettings {
            get {
                return ResourceManager.GetString("ColorsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات نمایشی ستون.
        /// </summary>
        public static string ColumnDispalySettings {
            get {
                return ResourceManager.GetString("ColumnDispalySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات نمایشی ستون.
        /// </summary>
        public static string ColumnDisplaySettings {
            get {
                return ResourceManager.GetString("ColumnDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات فیلتر ستون.
        /// </summary>
        public static string ColumnFilterSettings {
            get {
                return ResourceManager.GetString("ColumnFilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول ستون.
        /// </summary>
        public static string ColumnLength {
            get {
                return ResourceManager.GetString("ColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات ستون‌ها.
        /// </summary>
        public static string ColumnsSettings {
            get {
                return ResourceManager.GetString("ColumnsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات قالب ستون.
        /// </summary>
        public static string ColumnTemplateSettings {
            get {
                return ResourceManager.GetString("ColumnTemplateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام.
        /// </summary>
        public static string CompleteFormTask {
            get {
                return ResourceManager.GetString("CompleteFormTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این طراحی قابل ویرایش نیست. در صورت نیاز می‌توانید از آن کپی بگیرید..
        /// </summary>
        public static string ConfigIsNotModifiable {
            get {
                return ResourceManager.GetString("ConfigIsNotModifiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویژگی های طراحی.
        /// </summary>
        public static string ConfigSettings {
            get {
                return ResourceManager.GetString("ConfigSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبوردهای تنظیم شده.
        /// </summary>
        public static string ConfiguredDashboards {
            get {
                return ResourceManager.GetString("ConfiguredDashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور جدید.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار ثابت حداکثر.
        /// </summary>
        public static string ConstantMaxValue {
            get {
                return ResourceManager.GetString("ConstantMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار ثابت حداقل.
        /// </summary>
        public static string ConstantMinValue {
            get {
                return ResourceManager.GetString("ConstantMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل.
        /// </summary>
        public static string Containing {
            get {
                return ResourceManager.GetString("Containing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string ContextActive {
            get {
                return ResourceManager.GetString("ContextActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطرناک.
        /// </summary>
        public static string ContextDanger {
            get {
                return ResourceManager.GetString("ContextDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاع.
        /// </summary>
        public static string ContextInfo {
            get {
                return ResourceManager.GetString("ContextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موفق.
        /// </summary>
        public static string ContextSuccess {
            get {
                return ResourceManager.GetString("ContextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخطار.
        /// </summary>
        public static string ContextWarning {
            get {
                return ResourceManager.GetString("ContextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنترلر.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی قواعد.
        /// </summary>
        public static string ControllerDesign {
            get {
                return ResourceManager.GetString("ControllerDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کپی.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروجی CSV.
        /// </summary>
        public static string CSVExport {
            get {
                return ResourceManager.GetString("CSVExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جاری.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرگزارش‌های کنونی.
        /// </summary>
        public static string CurrentSubReports {
            get {
                return ResourceManager.GetString("CurrentSubReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد‌ها.
        /// </summary>
        public static string Dashboards {
            get {
                return ResourceManager.GetString("Dashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتفاع ویجت(پیکسل).
        /// </summary>
        public static string DashboardWidgetHeightLabel {
            get {
                return ResourceManager.GetString("DashboardWidgetHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض ویجت(یک تا دوازده).
        /// </summary>
        public static string DashboardWidgetWidthLabel {
            get {
                return ResourceManager.GetString("DashboardWidgetWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکسان‌سازی پایگاه داده.
        /// </summary>
        public static string DatabaseSynchronization {
            get {
                return ResourceManager.GetString("DatabaseSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع یکسان‌سازی.
        /// </summary>
        public static string DatabaseSynchronizationStart {
            get {
                return ResourceManager.GetString("DatabaseSynchronizationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقف یکسان‌سازی.
        /// </summary>
        public static string DatabaseSynchronizationStop {
            get {
                return ResourceManager.GetString("DatabaseSynchronizationStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش فرض.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار پیش فرض.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در تعاریف.
        /// </summary>
        public static string DefinitionsError {
            get {
                return ResourceManager.GetString("DefinitionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف و بازگشت.
        /// </summary>
        public static string DeleteAndReturn {
            get {
                return ResourceManager.GetString("DeleteAndReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نزولی.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی غیر فعال.
        /// </summary>
        public static string DisableAccess {
            get {
                return ResourceManager.GetString("DisableAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر فعال.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات نمایشی.
        /// </summary>
        public static string DisplaySettings {
            get {
                return ResourceManager.GetString("DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع نمایش.
        /// </summary>
        public static string DisplayType {
            get {
                return ResourceManager.GetString("DisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود قالب.
        /// </summary>
        public static string DownloadTemplate {
            get {
                return ResourceManager.GetString("DownloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود قالب با داده.
        /// </summary>
        public static string DownloadTemplateWithData {
            get {
                return ResourceManager.GetString("DownloadTemplateWithData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای آپلود، فایل را اینجا رها کنید..
        /// </summary>
        public static string DropFilesHere {
            get {
                return ResourceManager.GetString("DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش فرمول.
        /// </summary>
        public static string EditFormula {
            get {
                return ResourceManager.GetString("EditFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصلاح با اکسل.
        /// </summary>
        public static string EditViaExcel {
            get {
                return ResourceManager.GetString("EditViaExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودیت.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برابر با.
        /// </summary>
        public static string EqualWith {
            get {
                return ResourceManager.GetString("EqualWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکسل.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروجی اکسل.
        /// </summary>
        public static string ExcelExport {
            get {
                return ResourceManager.GetString("ExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود اطلاعات با اکسل.
        /// </summary>
        public static string ExcelImport {
            get {
                return ResourceManager.GetString("ExcelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات اکسل.
        /// </summary>
        public static string ExcelOperations {
            get {
                return ResourceManager.GetString("ExcelOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجود در لیست.
        /// </summary>
        public static string ExistInList {
            get {
                return ResourceManager.GetString("ExistInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string FalseTitle {
            get {
                return ResourceManager.GetString("FalseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر شده با.
        /// </summary>
        public static string FilteredBy {
            get {
                return ResourceManager.GetString("FilteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلترها.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات فیلتر.
        /// </summary>
        public static string FilterSettings {
            get {
                return ResourceManager.GetString("FilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فیلتر.
        /// </summary>
        public static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلتر.
        /// </summary>
        public static string FilterValue {
            get {
                return ResourceManager.GetString("FilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولین.
        /// </summary>
        public static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات پوشه.
        /// </summary>
        public static string FolderSettings {
            get {
                return ResourceManager.GetString("FolderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم‌ها.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع فرم.
        /// </summary>
        public static string FormSubject {
            get {
                return ResourceManager.GetString("FormSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فرم.
        /// </summary>
        public static string FormType {
            get {
                return ResourceManager.GetString("FormType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمول.
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن فرمول.
        /// </summary>
        public static string FormulaExpression {
            get {
                return ResourceManager.GetString("FormulaExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فرمول.
        /// </summary>
        public static string FormulaName {
            get {
                return ResourceManager.GetString("FormulaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختص گروه کاربری.
        /// </summary>
        public static string ForSpecificUserGroup {
            get {
                return ResourceManager.GetString("ForSpecificUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیشتر یا مساوی.
        /// </summary>
        public static string GreaterEqual {
            get {
                return ResourceManager.GetString("GreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیشتر از.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه‌بندی بر اساس.
        /// </summary>
        public static string GroupBy {
            get {
                return ResourceManager.GetString("GroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه‌بندی بر اساس.
        /// </summary>
        public static string GroupedBy {
            get {
                return ResourceManager.GetString("GroupedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست گروه‌بندی شده.
        /// </summary>
        public static string GroupedList {
            get {
                return ResourceManager.GetString("GroupedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی دارد.
        /// </summary>
        public static string HasAccess {
            get {
                return ResourceManager.GetString("HasAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتیجه شامل {0} رکورد است. احتمالن در تنظیمات ستون‌ها اشکالی وجود دارد..
        /// </summary>
        public static string HasCountWithoutRowsMessage {
            get {
                return ResourceManager.GetString("HasCountWithoutRowsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت افقی.
        /// </summary>
        public static string HorizontalPosition {
            get {
                return ResourceManager.GetString("HorizontalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیکون.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده‌ای برای نمایش وجود ندارد..
        /// </summary>
        public static string IndexNoData {
            get {
                return ResourceManager.GetString("IndexNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داخلی.
        /// </summary>
        public static string InlineSubReport {
            get {
                return ResourceManager.GetString("InlineSubReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشه ایران.
        /// </summary>
        public static string IranMap {
            get {
                return ResourceManager.GetString("IranMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرش به صفحه.
        /// </summary>
        public static string JumpToPage {
            get {
                return ResourceManager.GetString("JumpToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختص این طراحی.
        /// </summary>
        public static string JustForThisConfig {
            get {
                return ResourceManager.GetString("JustForThisConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب زبان.
        /// </summary>
        public static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین.
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چپ.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چپ به راست.
        /// </summary>
        public static string LeftToRight {
            get {
                return ResourceManager.GetString("LeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمتر یا مساوی.
        /// </summary>
        public static string LessEqual {
            get {
                return ResourceManager.GetString("LessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمتر از.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطوح.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیوندی.
        /// </summary>
        public static string Linked {
            get {
                return ResourceManager.GetString("Linked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرگزارش پیوندی.
        /// </summary>
        public static string LinkedSubReport {
            get {
                return ResourceManager.GetString("LinkedSubReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سامانه.
        /// </summary>
        public static string LoginToSystem {
            get {
                return ResourceManager.GetString("LoginToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشه.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وسط.
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میلی ثانیه.
        /// </summary>
        public static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دقیقه.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی های من.
        /// </summary>
        public static string MyAssignedAccess {
            get {
                return ResourceManager.GetString("MyAssignedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارهای من.
        /// </summary>
        public static string MyWorkItems {
            get {
                return ResourceManager.GetString("MyWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فضای نامی.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت تنظیم جدید.
        /// </summary>
        public static string NewSettingRegistration {
            get {
                return ResourceManager.GetString("NewSettingRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری جدید.
        /// </summary>
        public static string NewUsername {
            get {
                return ResourceManager.GetString("NewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعدی.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ کدام.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم وجود در لیست.
        /// </summary>
        public static string NotExistInList {
            get {
                return ResourceManager.GetString("NotExistInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه‌ی مورد نظر یافت نشد..
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک بار.
        /// </summary>
        public static string Once {
            get {
                return ResourceManager.GetString("Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس شناسه.
        /// </summary>
        public static string OrderById {
            get {
                return ResourceManager.GetString("OrderById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس متن.
        /// </summary>
        public static string OrderByText {
            get {
                return ResourceManager.GetString("OrderByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به ترتیب.
        /// </summary>
        public static string OrderedBy {
            get {
                return ResourceManager.GetString("OrderedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات ترتیب رکوردها.
        /// </summary>
        public static string OrderSettings {
            get {
                return ResourceManager.GetString("OrderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست سازمانی.
        /// </summary>
        public static string OrganizationalPosition {
            get {
                return ResourceManager.GetString("OrganizationalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوگوی سازمان.
        /// </summary>
        public static string OrganizationLogo {
            get {
                return ResourceManager.GetString("OrganizationLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا: صفحه یافت نشد.
        /// </summary>
        public static string PageNotFoundError {
            get {
                return ResourceManager.GetString("PageNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        public static string PageOf {
            get {
                return ResourceManager.GetString("PageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد.
        /// </summary>
        public static string PageRecord {
            get {
                return ResourceManager.GetString("PageRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحات.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string PageTo {
            get {
                return ResourceManager.GetString("PageTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لازم است رمزِ عبور به طولِ حداقل 6 و شاملِ حداقل یک کاراکتر عددی، یک کاراکتر با حروف کوچک و یک کاراکتر با حروف بزرگ باشد..
        /// </summary>
        public static string PasswordInstructions {
            get {
                return ResourceManager.GetString("PasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخصی.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا فایل را دانلود کرده و سپس مشاهده نمایید..
        /// </summary>
        public static string PleaseDownloadFirst {
            get {
                return ResourceManager.GetString("PleaseDownloadFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستون‌های قابل انتخاب.
        /// </summary>
        public static string PossibleColumns {
            get {
                return ResourceManager.GetString("PossibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابعاد گروه بندی قابل انتخاب.
        /// </summary>
        public static string PossibleReportDimensions {
            get {
                return ResourceManager.GetString("PossibleReportDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلی.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپ.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش نمایش گزارش.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرآیند.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرآیند‌ها.
        /// </summary>
        public static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابقه فرآیند.
        /// </summary>
        public static string ProcessHistory {
            get {
                return ResourceManager.GetString("ProcessHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویژگی ها.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همگانی.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان گزارش گیری.
        /// </summary>
        public static string QueryTime {
            get {
                return ResourceManager.GetString("QueryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد یافت نشد.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد رکوردها.
        /// </summary>
        public static string RecordsCount {
            get {
                return ResourceManager.GetString("RecordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز رسانی.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیم به روز رسانی گزارش.
        /// </summary>
        public static string RefreshTime {
            get {
                return ResourceManager.GetString("RefreshTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاصله تا به‌روز‌رسانی بعدی.
        /// </summary>
        public static string RefreshTimeInterval {
            get {
                return ResourceManager.GetString("RefreshTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری مجدد گزارش.
        /// </summary>
        public static string ReloadTheReport {
            get {
                return ResourceManager.GetString("ReloadTheReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا به خاطرت نگه دار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذفِ فایل.
        /// </summary>
        public static string RemoveFile {
            get {
                return ResourceManager.GetString("RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر نام.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره تکرار.
        /// </summary>
        public static string RepeatPeriod {
            get {
                return ResourceManager.GetString("RepeatPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار شونده.
        /// </summary>
        public static string Repetetive {
            get {
                return ResourceManager.GetString("Repetetive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف طراحی جدید برای گزارش.
        /// </summary>
        public static string ReportAddNewConfig {
            get {
                return ResourceManager.GetString("ReportAddNewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افقی.
        /// </summary>
        public static string ReportAsHorizontalColumn {
            get {
                return ResourceManager.GetString("ReportAsHorizontalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی گزارش‌ها.
        /// </summary>
        public static string ReportDesigns {
            get {
                return ResourceManager.GetString("ReportDesigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابعاد گروه بندی.
        /// </summary>
        public static string ReportDimensions {
            get {
                return ResourceManager.GetString("ReportDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش تجمیعی.
        /// </summary>
        public static string GroupByList {
            get {
                return ResourceManager.GetString("GroupByList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ گزارش.
        /// </summary>
        public static string ReportingDate {
            get {
                return ResourceManager.GetString("ReportingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت گزارش.
        /// </summary>
        public static string ReportingTime {
            get {
                return ResourceManager.GetString("ReportingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش‌ها.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمانبندی اجرای طراحی.
        /// </summary>
        public static string ReportScheduling {
            get {
                return ResourceManager.GetString("ReportScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات گزارش.
        /// </summary>
        public static string ReportSettings {
            get {
                return ResourceManager.GetString("ReportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده در تولتیپ.
        /// </summary>
        public static string ReportUseColumnInTooltips {
            get {
                return ResourceManager.GetString("ReportUseColumnInTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلاش مجدد.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راست.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راست به چپ.
        /// </summary>
        public static string RightToLeft {
            get {
                return ResourceManager.GetString("RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و جدید.
        /// </summary>
        public static string SaveAndNew {
            get {
                return ResourceManager.GetString("SaveAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و بازگشت.
        /// </summary>
        public static string SaveAndReturn {
            get {
                return ResourceManager.GetString("SaveAndReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره مقادیر فیلتر.
        /// </summary>
        public static string SaveFilterValues {
            get {
                return ResourceManager.GetString("SaveFilterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت فیلتر جدید.
        /// </summary>
        public static string SaveNewFilter {
            get {
                return ResourceManager.GetString("SaveNewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره مقادیر فیلتر زمانبندی.
        /// </summary>
        public static string SaveScheduleFilter {
            get {
                return ResourceManager.GetString("SaveScheduleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات زمانبندی.
        /// </summary>
        public static string ScheduleSettings {
            get {
                return ResourceManager.GetString("ScheduleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع زمانبندی.
        /// </summary>
        public static string ScheduleType {
            get {
                return ResourceManager.GetString("ScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثانیه.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده تغییرات.
        /// </summary>
        public static string SeeChanges {
            get {
                return ResourceManager.GetString("SeeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم‌های موضوعی قابل انتخاب.
        /// </summary>
        public static string SelectableSubjectForms {
            get {
                return ResourceManager.GetString("SelectableSubjectForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستون‌های انتخاب شده.
        /// </summary>
        public static string SelectedColumns {
            get {
                return ResourceManager.GetString("SelectedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستون‌های نمایشی.
        /// </summary>
        public static string SelectedReportColumns {
            get {
                return ResourceManager.GetString("SelectedReportColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم‌های موضوعی انتخاب شده.
        /// </summary>
        public static string SelectedSubjectForms {
            get {
                return ResourceManager.GetString("SelectedSubjectForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا داخلی در سرویس دهنده.
        /// </summary>
        public static string ServerInternalError {
            get {
                return ResourceManager.GetString("ServerInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای سمت سرویس دهنده.
        /// </summary>
        public static string ServerSideError {
            get {
                return ResourceManager.GetString("ServerSideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکسان سازی جداول پایه.
        /// </summary>
        public static string SetEnumerationItems {
            get {
                return ResourceManager.GetString("SetEnumerationItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحات خاص.
        /// </summary>
        public static string SpecialPages {
            get {
                return ResourceManager.GetString("SpecialPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکانات ویژه‌ی سیستم.
        /// </summary>
        public static string SpecialSystemFeatures {
            get {
                return ResourceManager.GetString("SpecialSystemFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع فرآیند.
        /// </summary>
        public static string StartProcess {
            get {
                return ResourceManager.GetString("StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع با.
        /// </summary>
        public static string StartWith {
            get {
                return ResourceManager.GetString("StartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرگزارش.
        /// </summary>
        public static string SubReport {
            get {
                return ResourceManager.GetString("SubReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام زیرگزارش.
        /// </summary>
        public static string SubReportName {
            get {
                return ResourceManager.GetString("SubReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرگزارش‌ها.
        /// </summary>
        public static string SubReports {
            get {
                return ResourceManager.GetString("SubReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات زیر گزارش.
        /// </summary>
        public static string SubReportSettings {
            get {
                return ResourceManager.GetString("SubReportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرط قالب.
        /// </summary>
        public static string TemplateCondition {
            get {
                return ResourceManager.GetString("TemplateCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام قالب.
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ متن.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت متن.
        /// </summary>
        public static string TextDirection {
            get {
                return ResourceManager.GetString("TextDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالا.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string TrueTitle {
            get {
                return ResourceManager.GetString("TrueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدمِ حذفِ فایل.
        /// </summary>
        public static string UndoRemoveFile {
            get {
                return ResourceManager.GetString("UndoRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نابرابر با.
        /// </summary>
        public static string UnequalWith {
            get {
                return ResourceManager.GetString("UnequalWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلترهای پرکاربرد.
        /// </summary>
        public static string UsefulFilters {
            get {
                return ResourceManager.GetString("UsefulFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه کاربری.
        /// </summary>
        public static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه های کاربری.
        /// </summary>
        public static string UserGroups {
            get {
                return ResourceManager.GetString("UserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کد ارسالی برای ورود به سامانه.
        /// </summary>
        public static string VerifyLoginToSystem {
            get {
                return ResourceManager.GetString("VerifyLoginToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت عمودی.
        /// </summary>
        public static string VerticalPosition {
            get {
                return ResourceManager.GetString("VerticalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش  جایگاه فرم در جریان کار.
        /// </summary>
        public static string ViewFormInWorkFlow {
            get {
                return ResourceManager.GetString("ViewFormInWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفته.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات ویجت.
        /// </summary>
        public static string WidgetSettings {
            get {
                return ResourceManager.GetString("WidgetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشه جهان.
        /// </summary>
        public static string WorldMap {
            get {
                return ResourceManager.GetString("WorldMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
