//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Bpms.UI.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Bpms.UI.Resources.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت ناموفق بود..
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنین طراحی موجود نیست..
        /// </summary>
        public static string ConfigNotFound {
            get {
                return ResourceManager.GetString("ConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت ایجاد شد..
        /// </summary>
        public static string CreatedSuccessfully {
            get {
                return ResourceManager.GetString("CreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف با خطا مواجه شد..
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان طراحی وجود ندارد..
        /// </summary>
        public static string DesignFeatureIsNotEnabled {
            get {
                return ResourceManager.GetString("DesignFeatureIsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت انجام شد..
        /// </summary>
        public static string DoneSuccessfully {
            get {
                return ResourceManager.GetString("DoneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنین فرمی موجود نیست..
        /// </summary>
        public static string FormNotFound {
            get {
                return ResourceManager.GetString("FormNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی نادرست بود..
        /// </summary>
        public static string IncorrectCaptcha {
            get {
                return ResourceManager.GetString("IncorrectCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده صحیح نمی باشد.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست نامعتبر.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت طراحی جدید با موفقیت انجام شد..
        /// </summary>
        public static string NewConfigAddedSuccessfully {
            get {
                return ResourceManager.GetString("NewConfigAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت طراحی جدید برای گزارش با خطا مواجه شد..
        /// </summary>
        public static string NewConfigAdditionFailed {
            get {
                return ResourceManager.GetString("NewConfigAdditionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل انتخاب نشده است..
        /// </summary>
        public static string NoSelectedFile {
            get {
                return ResourceManager.GetString("NoSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما به این صفحه دسترسی ندارید..
        /// </summary>
        public static string PageAccessDenied {
            get {
                return ResourceManager.GetString("PageAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه مورد نظر موجود نیست..
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا دوباره وارد شوید..
        /// </summary>
        public static string PleaseLoginAgain {
            get {
                return ResourceManager.GetString("PleaseLoginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد انتخاب نشده است..
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد انتخاب نشده است و یا در وضعیت دلخواه قرار ندارد..
        /// </summary>
        public static string RecordNotFoundOrDifferentState {
            get {
                return ResourceManager.GetString("RecordNotFoundOrDifferentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما به این گزارش دسترسی ندارید..
        /// </summary>
        public static string ReportAccessDenied {
            get {
                return ResourceManager.GetString("ReportAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دسترسی طراحی گزارش ندارید..
        /// </summary>
        public static string ReportDesignAccessDenied {
            get {
                return ResourceManager.GetString("ReportDesignAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات انجام نشد..
        /// </summary>
        public static string SaveWasNotSuccessful {
            get {
                return ResourceManager.GetString("SaveWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای سیستم.
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کاربر در این سامانه تعریف نشده است..
        /// </summary>
        public static string ThisUserDoesNotExist {
            get {
                return ResourceManager.GetString("ThisUserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کار این پرونده در این مرحله قبلا انجام شده است..
        /// </summary>
        public static string WorkAlreadyDone {
            get {
                return ResourceManager.GetString("WorkAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است..
        /// </summary>
        public static string WrongUsernameOrPassword {
            get {
                return ResourceManager.GetString("WrongUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان طراحی فرآیند برای شما وجود ندارد..
        /// </summary>
        public static string YouCantDesignProcesses {
            get {
                return ResourceManager.GetString("YouCantDesignProcesses", resourceCulture);
            }
        }
    }
}
