//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Bpms.UI.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewTexts_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewTexts_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Bpms.UI.MVC.Resources.ViewTexts.en", typeof(ViewTexts_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this page..
        /// </summary>
        public static string AccessDeniedHeader {
            get {
                return ResourceManager.GetString("AccessDeniedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Lack of Access.
        /// </summary>
        public static string AccessDeniedTitle {
            get {
                return ResourceManager.GetString("AccessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Level.
        /// </summary>
        public static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access via User Group.
        /// </summary>
        public static string AccessViaUserGroup {
            get {
                return ResourceManager.GetString("AccessViaUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Formula.
        /// </summary>
        public static string AddFormula {
            get {
                return ResourceManager.GetString("AddFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Config.
        /// </summary>
        public static string AddNewConfig {
            get {
                return ResourceManager.GetString("AddNewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Filter.
        /// </summary>
        public static string AddNewFilter {
            get {
                return ResourceManager.GetString("AddNewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Record.
        /// </summary>
        public static string AddNewRecord {
            get {
                return ResourceManager.GetString("AddNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Template.
        /// </summary>
        public static string AddNewTemplate {
            get {
                return ResourceManager.GetString("AddNewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Possible Sub Report.
        /// </summary>
        public static string AddPossibleSubReport {
            get {
                return ResourceManager.GetString("AddPossibleSubReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Design.
        /// </summary>
        public static string AddReportConfig {
            get {
                return ResourceManager.GetString("AddReportConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Schedule.
        /// </summary>
        public static string AddSchedule {
            get {
                return ResourceManager.GetString("AddSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub-Report.
        /// </summary>
        public static string AddSubReport {
            get {
                return ResourceManager.GetString("AddSubReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Widget.
        /// </summary>
        public static string AddWidget {
            get {
                return ResourceManager.GetString("AddWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Tools.
        /// </summary>
        public static string AdminTools {
            get {
                return ResourceManager.GetString("AdminTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation Filter.
        /// </summary>
        public static string AggregationFilter {
            get {
                return ResourceManager.GetString("AggregationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllTitle {
            get {
                return ResourceManager.GetString("AllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Settings.
        /// </summary>
        public static string ApplySettings {
            get {
                return ResourceManager.GetString("ApplySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply User Settings.
        /// </summary>
        public static string ApplyUserSettings {
            get {
                return ResourceManager.GetString("ApplyUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Access.
        /// </summary>
        public static string AssignAccess {
            get {
                return ResourceManager.GetString("AssignAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Create Process.
        /// </summary>
        public static string BulkCreateProcess {
            get {
                return ResourceManager.GetString("BulkCreateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Edit Entity.
        /// </summary>
        public static string BulkEditEntity {
            get {
                return ResourceManager.GetString("BulkEditEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Operations.
        /// </summary>
        public static string BulkOperations {
            get {
                return ResourceManager.GetString("BulkOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Sub-Report Type.
        /// </summary>
        public static string ChangeSubReportType {
            get {
                return ResourceManager.GetString("ChangeSubReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Username And Password.
        /// </summary>
        public static string ChangeUsernameAndPassword {
            get {
                return ResourceManager.GetString("ChangeUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Users Password.
        /// </summary>
        public static string ChangeUsersPassword {
            get {
                return ResourceManager.GetString("ChangeUsersPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Settings.
        /// </summary>
        public static string ChartSettings {
            get {
                return ResourceManager.GetString("ChartSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Type.
        /// </summary>
        public static string ChartType {
            get {
                return ResourceManager.GetString("ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a File.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        public static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter Form.
        /// </summary>
        public static string ClearFilterForm {
            get {
                return ResourceManager.GetString("ClearFilterForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Settings.
        /// </summary>
        public static string ColorsSettings {
            get {
                return ResourceManager.GetString("ColorsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column  Display Settings.
        /// </summary>
        public static string ColumnDispalySettings {
            get {
                return ResourceManager.GetString("ColumnDispalySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Display Settings.
        /// </summary>
        public static string ColumnDisplaySettings {
            get {
                return ResourceManager.GetString("ColumnDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Filter Settings.
        /// </summary>
        public static string ColumnFilterSettings {
            get {
                return ResourceManager.GetString("ColumnFilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Length.
        /// </summary>
        public static string ColumnLength {
            get {
                return ResourceManager.GetString("ColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns Settings.
        /// </summary>
        public static string ColumnsSettings {
            get {
                return ResourceManager.GetString("ColumnsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Template Settings.
        /// </summary>
        public static string ColumnTemplateSettings {
            get {
                return ResourceManager.GetString("ColumnTemplateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string CompleteFormTask {
            get {
                return ResourceManager.GetString("CompleteFormTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This config is not modifiable. You can copy it if you need a modification..
        /// </summary>
        public static string ConfigIsNotModifiable {
            get {
                return ResourceManager.GetString("ConfigIsNotModifiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Settings.
        /// </summary>
        public static string ConfigSettings {
            get {
                return ResourceManager.GetString("ConfigSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Dashboards.
        /// </summary>
        public static string ConfiguredDashboards {
            get {
                return ResourceManager.GetString("ConfiguredDashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Maximum Value.
        /// </summary>
        public static string ConstantMaxValue {
            get {
                return ResourceManager.GetString("ConstantMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Minimum Value.
        /// </summary>
        public static string ConstantMinValue {
            get {
                return ResourceManager.GetString("ConstantMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containing.
        /// </summary>
        public static string Containing {
            get {
                return ResourceManager.GetString("Containing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ContextActive {
            get {
                return ResourceManager.GetString("ContextActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger.
        /// </summary>
        public static string ContextDanger {
            get {
                return ResourceManager.GetString("ContextDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string ContextInfo {
            get {
                return ResourceManager.GetString("ContextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string ContextSuccess {
            get {
                return ResourceManager.GetString("ContextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ContextWarning {
            get {
                return ResourceManager.GetString("ContextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Design.
        /// </summary>
        public static string ControllerDesign {
            get {
                return ResourceManager.GetString("ControllerDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Export.
        /// </summary>
        public static string CSVExport {
            get {
                return ResourceManager.GetString("CSVExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Sub Reports.
        /// </summary>
        public static string CurrentSubReports {
            get {
                return ResourceManager.GetString("CurrentSubReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        public static string Dashboards {
            get {
                return ResourceManager.GetString("Dashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget Height (px).
        /// </summary>
        public static string DashboardWidgetHeightLabel {
            get {
                return ResourceManager.GetString("DashboardWidgetHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget Width (1 to 12).
        /// </summary>
        public static string DashboardWidgetWidthLabel {
            get {
                return ResourceManager.GetString("DashboardWidgetWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing Database With Model.
        /// </summary>
        public static string DatabaseSynchronization {
            get {
                return ResourceManager.GetString("DatabaseSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Synchronization.
        /// </summary>
        public static string DatabaseSynchronizationStart {
            get {
                return ResourceManager.GetString("DatabaseSynchronizationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Synchronization.
        /// </summary>
        public static string DatabaseSynchronizationStop {
            get {
                return ResourceManager.GetString("DatabaseSynchronizationStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions Error.
        /// </summary>
        public static string DefinitionsError {
            get {
                return ResourceManager.GetString("DefinitionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete and Return.
        /// </summary>
        public static string DeleteAndReturn {
            get {
                return ResourceManager.GetString("DeleteAndReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Access.
        /// </summary>
        public static string DisableAccess {
            get {
                return ResourceManager.GetString("DisableAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        public static string DisplaySettings {
            get {
                return ResourceManager.GetString("DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Type.
        /// </summary>
        public static string DisplayType {
            get {
                return ResourceManager.GetString("DisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template.
        /// </summary>
        public static string DownloadTemplate {
            get {
                return ResourceManager.GetString("DownloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template With Data.
        /// </summary>
        public static string DownloadTemplateWithData {
            get {
                return ResourceManager.GetString("DownloadTemplateWithData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files here..
        /// </summary>
        public static string DropFilesHere {
            get {
                return ResourceManager.GetString("DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Formula.
        /// </summary>
        public static string EditFormula {
            get {
                return ResourceManager.GetString("EditFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit via Excel.
        /// </summary>
        public static string EditViaExcel {
            get {
                return ResourceManager.GetString("EditViaExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        public static string EqualWith {
            get {
                return ResourceManager.GetString("EqualWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Export.
        /// </summary>
        public static string ExcelExport {
            get {
                return ResourceManager.GetString("ExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Import.
        /// </summary>
        public static string ExcelImport {
            get {
                return ResourceManager.GetString("ExcelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Operations.
        /// </summary>
        public static string ExcelOperations {
            get {
                return ResourceManager.GetString("ExcelOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist In List.
        /// </summary>
        public static string ExistInList {
            get {
                return ResourceManager.GetString("ExistInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string FalseTitle {
            get {
                return ResourceManager.GetString("FalseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered By.
        /// </summary>
        public static string FilteredBy {
            get {
                return ResourceManager.GetString("FilteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Settings.
        /// </summary>
        public static string FilterSettings {
            get {
                return ResourceManager.GetString("FilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Type.
        /// </summary>
        public static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Value.
        /// </summary>
        public static string FilterValue {
            get {
                return ResourceManager.GetString("FilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Settings.
        /// </summary>
        public static string FolderSettings {
            get {
                return ResourceManager.GetString("FolderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Subject.
        /// </summary>
        public static string FormSubject {
            get {
                return ResourceManager.GetString("FormSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Type.
        /// </summary>
        public static string FormType {
            get {
                return ResourceManager.GetString("FormType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Expression.
        /// </summary>
        public static string FormulaExpression {
            get {
                return ResourceManager.GetString("FormulaExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Name.
        /// </summary>
        public static string FormulaName {
            get {
                return ResourceManager.GetString("FormulaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Specific User Group.
        /// </summary>
        public static string ForSpecificUserGroup {
            get {
                return ResourceManager.GetString("ForSpecificUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Equal.
        /// </summary>
        public static string GreaterEqual {
            get {
                return ResourceManager.GetString("GreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By.
        /// </summary>
        public static string GroupBy {
            get {
                return ResourceManager.GetString("GroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped By.
        /// </summary>
        public static string GroupedBy {
            get {
                return ResourceManager.GetString("GroupedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped List.
        /// </summary>
        public static string GroupedList {
            get {
                return ResourceManager.GetString("GroupedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string HasAccess {
            get {
                return ResourceManager.GetString("HasAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result contains {0} records. There is probably a problem in columns settings..
        /// </summary>
        public static string HasCountWithoutRowsMessage {
            get {
                return ResourceManager.GetString("HasCountWithoutRowsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Position.
        /// </summary>
        public static string HorizontalPosition {
            get {
                return ResourceManager.GetString("HorizontalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data available..
        /// </summary>
        public static string IndexNoData {
            get {
                return ResourceManager.GetString("IndexNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline.
        /// </summary>
        public static string InlineSubReport {
            get {
                return ResourceManager.GetString("InlineSubReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran Map.
        /// </summary>
        public static string IranMap {
            get {
                return ResourceManager.GetString("IranMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump To Page.
        /// </summary>
        public static string JumpToPage {
            get {
                return ResourceManager.GetString("JumpToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just For This Design.
        /// </summary>
        public static string JustForThisConfig {
            get {
                return ResourceManager.GetString("JustForThisConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Selection.
        /// </summary>
        public static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left To Right.
        /// </summary>
        public static string LeftToRight {
            get {
                return ResourceManager.GetString("LeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Equal.
        /// </summary>
        public static string LessEqual {
            get {
                return ResourceManager.GetString("LessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked.
        /// </summary>
        public static string Linked {
            get {
                return ResourceManager.GetString("Linked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Sub Report.
        /// </summary>
        public static string LinkedSubReport {
            get {
                return ResourceManager.GetString("LinkedSubReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginToSystem {
            get {
                return ResourceManager.GetString("LoginToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        public static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Assigned Accesses.
        /// </summary>
        public static string MyAssignedAccess {
            get {
                return ResourceManager.GetString("MyAssignedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Work Items.
        /// </summary>
        public static string MyWorkItems {
            get {
                return ResourceManager.GetString("MyWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Configuration.
        /// </summary>
        public static string NewSettingRegistration {
            get {
                return ResourceManager.GetString("NewSettingRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Username.
        /// </summary>
        public static string NewUsername {
            get {
                return ResourceManager.GetString("NewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Exist In List.
        /// </summary>
        public static string NotExistInList {
            get {
                return ResourceManager.GetString("NotExistInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once.
        /// </summary>
        public static string Once {
            get {
                return ResourceManager.GetString("Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Id.
        /// </summary>
        public static string OrderById {
            get {
                return ResourceManager.GetString("OrderById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Text.
        /// </summary>
        public static string OrderByText {
            get {
                return ResourceManager.GetString("OrderByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered By.
        /// </summary>
        public static string OrderedBy {
            get {
                return ResourceManager.GetString("OrderedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Settings.
        /// </summary>
        public static string OrderSettings {
            get {
                return ResourceManager.GetString("OrderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Position.
        /// </summary>
        public static string OrganizationalPosition {
            get {
                return ResourceManager.GetString("OrganizationalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Logo.
        /// </summary>
        public static string OrganizationLogo {
            get {
                return ResourceManager.GetString("OrganizationLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Page Not Found.
        /// </summary>
        public static string PageNotFoundError {
            get {
                return ResourceManager.GetString("PageNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string PageOf {
            get {
                return ResourceManager.GetString("PageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string PageRecord {
            get {
                return ResourceManager.GetString("PageRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string PageTo {
            get {
                return ResourceManager.GetString("PageTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password length must be at least 6 and it must contain at least one numeric, one capital-case and one lower-case character..
        /// </summary>
        public static string PasswordInstructions {
            get {
                return ResourceManager.GetString("PasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please download and then open the file..
        /// </summary>
        public static string PleaseDownloadFirst {
            get {
                return ResourceManager.GetString("PleaseDownloadFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Columns.
        /// </summary>
        public static string PossibleColumns {
            get {
                return ResourceManager.GetString("PossibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Dimensions.
        /// </summary>
        public static string PossibleReportDimensions {
            get {
                return ResourceManager.GetString("PossibleReportDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process History.
        /// </summary>
        public static string ProcessHistory {
            get {
                return ResourceManager.GetString("ProcessHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It took.
        /// </summary>
        public static string QueryTime {
            get {
                return ResourceManager.GetString("QueryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Found.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Count.
        /// </summary>
        public static string RecordsCount {
            get {
                return ResourceManager.GetString("RecordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Time.
        /// </summary>
        public static string RefreshTime {
            get {
                return ResourceManager.GetString("RefreshTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Time Interval.
        /// </summary>
        public static string RefreshTimeInterval {
            get {
                return ResourceManager.GetString("RefreshTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string ReloadTheReport {
            get {
                return ResourceManager.GetString("ReloadTheReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File.
        /// </summary>
        public static string RemoveFile {
            get {
                return ResourceManager.GetString("RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition Period.
        /// </summary>
        public static string RepeatPeriod {
            get {
                return ResourceManager.GetString("RepeatPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetetive.
        /// </summary>
        public static string Repetetive {
            get {
                return ResourceManager.GetString("Repetetive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Config.
        /// </summary>
        public static string ReportAddNewConfig {
            get {
                return ResourceManager.GetString("ReportAddNewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string ReportAsHorizontalColumn {
            get {
                return ResourceManager.GetString("ReportAsHorizontalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Designs.
        /// </summary>
        public static string ReportDesigns {
            get {
                return ResourceManager.GetString("ReportDesigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string ReportDimensions {
            get {
                return ResourceManager.GetString("ReportDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string GroupByList {
            get {
                return ResourceManager.GetString("GroupByList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ReportingDate {
            get {
                return ResourceManager.GetString("ReportingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ReportingTime {
            get {
                return ResourceManager.GetString("ReportingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling.
        /// </summary>
        public static string ReportScheduling {
            get {
                return ResourceManager.GetString("ReportScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Settings.
        /// </summary>
        public static string ReportSettings {
            get {
                return ResourceManager.GetString("ReportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use in tooltips.
        /// </summary>
        public static string ReportUseColumnInTooltips {
            get {
                return ResourceManager.GetString("ReportUseColumnInTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right To Left.
        /// </summary>
        public static string RightToLeft {
            get {
                return ResourceManager.GetString("RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and New.
        /// </summary>
        public static string SaveAndNew {
            get {
                return ResourceManager.GetString("SaveAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Return.
        /// </summary>
        public static string SaveAndReturn {
            get {
                return ResourceManager.GetString("SaveAndReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Filter.
        /// </summary>
        public static string SaveFilterValues {
            get {
                return ResourceManager.GetString("SaveFilterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Filter As.
        /// </summary>
        public static string SaveNewFilter {
            get {
                return ResourceManager.GetString("SaveNewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Schedule Filter.
        /// </summary>
        public static string SaveScheduleFilter {
            get {
                return ResourceManager.GetString("SaveScheduleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Settings.
        /// </summary>
        public static string ScheduleSettings {
            get {
                return ResourceManager.GetString("ScheduleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Type.
        /// </summary>
        public static string ScheduleType {
            get {
                return ResourceManager.GetString("ScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Changes.
        /// </summary>
        public static string SeeChanges {
            get {
                return ResourceManager.GetString("SeeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectable Subject Forms.
        /// </summary>
        public static string SelectableSubjectForms {
            get {
                return ResourceManager.GetString("SelectableSubjectForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Columns.
        /// </summary>
        public static string SelectedColumns {
            get {
                return ResourceManager.GetString("SelectedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Columns.
        /// </summary>
        public static string SelectedReportColumns {
            get {
                return ResourceManager.GetString("SelectedReportColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Subject Forms.
        /// </summary>
        public static string SelectedSubjectForms {
            get {
                return ResourceManager.GetString("SelectedSubjectForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Internal Error.
        /// </summary>
        public static string ServerInternalError {
            get {
                return ResourceManager.GetString("ServerInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Side Error.
        /// </summary>
        public static string ServerSideError {
            get {
                return ResourceManager.GetString("ServerSideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Pages.
        /// </summary>
        public static string SpecialPages {
            get {
                return ResourceManager.GetString("SpecialPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special System Features.
        /// </summary>
        public static string SpecialSystemFeatures {
            get {
                return ResourceManager.GetString("SpecialSystemFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Process.
        /// </summary>
        public static string StartProcess {
            get {
                return ResourceManager.GetString("StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start With.
        /// </summary>
        public static string StartWith {
            get {
                return ResourceManager.GetString("StartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Report.
        /// </summary>
        public static string SubReport {
            get {
                return ResourceManager.GetString("SubReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Report Name.
        /// </summary>
        public static string SubReportName {
            get {
                return ResourceManager.GetString("SubReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Reports.
        /// </summary>
        public static string SubReports {
            get {
                return ResourceManager.GetString("SubReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Report Settings.
        /// </summary>
        public static string SubReportSettings {
            get {
                return ResourceManager.GetString("SubReportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Condition.
        /// </summary>
        public static string TemplateCondition {
            get {
                return ResourceManager.GetString("TemplateCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Direction.
        /// </summary>
        public static string TextDirection {
            get {
                return ResourceManager.GetString("TextDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TrueTitle {
            get {
                return ResourceManager.GetString("TrueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo File Remove.
        /// </summary>
        public static string UndoRemoveFile {
            get {
                return ResourceManager.GetString("UndoRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unequal with.
        /// </summary>
        public static string UnequalWith {
            get {
                return ResourceManager.GetString("UnequalWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Filters.
        /// </summary>
        public static string UsefulFilters {
            get {
                return ResourceManager.GetString("UsefulFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        public static string UserGroups {
            get {
                return ResourceManager.GetString("UserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Position.
        /// </summary>
        public static string VerticalPosition {
            get {
                return ResourceManager.GetString("VerticalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Form In Work Flow.
        /// </summary>
        public static string ViewFormInWorkFlow {
            get {
                return ResourceManager.GetString("ViewFormInWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget Settings.
        /// </summary>
        public static string WidgetSettings {
            get {
                return ResourceManager.GetString("WidgetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Map.
        /// </summary>
        public static string WorldMap {
            get {
                return ResourceManager.GetString("WorldMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
