//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Bpms.Domain.Models.Cmmn.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Bpms.Domain.Models.Cmmn.Data.Resources.DataTexts", typeof(DataTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Collation.
        /// </summary>
        public static string CheckCollation {
            get {
                return ResourceManager.GetString("CheckCollation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکسان‌سازی کلید‌های خارجی.
        /// </summary>
        public static string CheckForeignKey {
            get {
                return ResourceManager.GetString("CheckForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکسان‌سازی ایندکس‌ها.
        /// </summary>
        public static string CheckIndexes {
            get {
                return ResourceManager.GetString("CheckIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاکسازی کل پایگاه داده در ابتدا.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد ایندکس به ازای کلیدخارجی.
        /// </summary>
        public static string CreateForeignKeyIndex {
            get {
                return ResourceManager.GetString("CreateForeignKeyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فیزیکی جداول ناشناخته.
        /// </summary>
        public static string DoDropUndefinedTables {
            get {
                return ResourceManager.GetString("DoDropUndefinedTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف جداول ناشناخته.
        /// </summary>
        public static string DoRenameUndefinedTables {
            get {
                return ResourceManager.GetString("DoRenameUndefinedTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف ایندکس‌های ناشناخته.
        /// </summary>
        public static string DropExtraIndex {
            get {
                return ResourceManager.GetString("DropExtraIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف ایندکس‌های کلیدخارجی.
        /// </summary>
        public static string DropForeignKeyIndex {
            get {
                return ResourceManager.GetString("DropForeignKeyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فیزیکی فیلدهای ناشناخته.
        /// </summary>
        public static string DropUndefinedField {
            get {
                return ResourceManager.GetString("DropUndefinedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فیزیکی ویوهای ناشناخته.
        /// </summary>
        public static string DropUndefinedViews {
            get {
                return ResourceManager.GetString("DropUndefinedViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازسازی ایندکس‌ها.
        /// </summary>
        public static string RebuildIndex {
            get {
                return ResourceManager.GetString("RebuildIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش دیدگاه.
        /// </summary>
        public static string RefreshView {
            get {
                return ResourceManager.GetString("RefreshView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فیلدهای ناشناخته.
        /// </summary>
        public static string RenameUndefinedField {
            get {
                return ResourceManager.GetString("RenameUndefinedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف ویوهای ناشناخته.
        /// </summary>
        public static string RenameUndefinedViews {
            get {
                return ResourceManager.GetString("RenameUndefinedViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن یا به روز رسانی رکوردهای ثابت جداول پایه.
        /// </summary>
        public static string SetEnumerationItems {
            get {
                return ResourceManager.GetString("SetEnumerationItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودیت خاص.
        /// </summary>
        public static string SpecificEntity {
            get {
                return ResourceManager.GetString("SpecificEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فضای نامی خاص.
        /// </summary>
        public static string SpecificNamespace {
            get {
                return ResourceManager.GetString("SpecificNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکسان سازی فایل گروه.
        /// </summary>
        public static string SyncFileGroups {
            get {
                return ResourceManager.GetString("SyncFileGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکسان‌سازی متادیتا.
        /// </summary>
        public static string SyncMetaData {
            get {
                return ResourceManager.GetString("SyncMetaData", resourceCulture);
            }
        }
    }
}
