//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Bpms.Infrastructure.Features.Cmmn.Forms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Bpms.Infrastructure.Features.Cmmn.Forms.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUE/FALSE.
        /// </summary>
        internal static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل اکسل خوانده نشد..
        /// </summary>
        internal static string CouldNotReadExcelFile {
            get {
                return ResourceManager.GetString("CouldNotReadExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد اعشاری.
        /// </summary>
        internal static string DecimalNumber {
            get {
                return ResourceManager.GetString("DecimalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایراد در آپلود فایل.
        /// </summary>
        internal static string ErrorInUploadFile {
            get {
                return ResourceManager.GetString("ErrorInUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام صفحه اول اکسل نامعتبر  است..
        /// </summary>
        internal static string ExcelFirstSheetIsInvalid {
            get {
                return ResourceManager.GetString("ExcelFirstSheetIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صفحه اصلی اکسل سرستون نامعتبر است..
        /// </summary>
        internal static string ExcelMainSheetHeaderIsInvalid {
            get {
                return ResourceManager.GetString("ExcelMainSheetHeaderIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقویم میلادی.
        /// </summary>
        internal static string GregorianCalendar {
            get {
                return ResourceManager.GetString("GregorianCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعتبر است..
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرستون‌ صفحه نامعتبر.
        /// </summary>
        internal static string InvalidExcelSheetHeader {
            get {
                return ResourceManager.GetString("InvalidExcelSheetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام صفحه نامتعبر است.
        /// </summary>
        internal static string InvalidExcelSheetName {
            get {
                return ResourceManager.GetString("InvalidExcelSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول.
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد اجباری فرم موجود نیست.
        /// </summary>
        internal static string MissingMandatoryMessage {
            get {
                return ResourceManager.GetString("MissingMandatoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان افزودن مقادیر متعدد با استفاده از جدا کننده ویرگول وجود دارد..
        /// </summary>
        internal static string MultipleComboWithCommaSeperator {
            get {
                return ResourceManager.GetString("MultipleComboWithCommaSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در موجودیت مرتبط یافت نشد و امکان اضافه شدن خودکار آن وحود ندارد..
        /// </summary>
        internal static string NotFoundAndCannotSaveAuto {
            get {
                return ResourceManager.GetString("NotFoundAndCannotSaveAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ارتباطی مافوق.
        /// </summary>
        internal static string ParentKey {
            get {
                return ResourceManager.GetString("ParentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید اصلی.
        /// </summary>
        internal static string PrimaryKey {
            get {
                return ResourceManager.GetString("PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ارتباطی.
        /// </summary>
        internal static string RelationshipKey {
            get {
                return ResourceManager.GetString("RelationshipKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای سیستم.
        /// </summary>
        internal static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت زمان.
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
    }
}
